### PR TITLE
README: Make it a bit more obvious what's needed for manual PR checks

### LINKED ISSUE #26: Allow CLA check from commits sha
Today I fixed the commit author info on jquery/qunit#751 to make it pass on the CLA check. The commit wasn't originally mine and I figured out the only way to double check the CLA information was creating another PR.

I would be great to have anything to check the CLA through a commit SHA, even it's on a temp branch on the github project's repo. 

from IRC, @scottgonzalez talked about a binary, which would also solve this problem:

```
$ jquery-audit-commit SHA
```

### PR DESCRIPTION
**Pull request by jzaefferer**
Fixes #26

@leobalter @rxaviers can you take a look at this? The information was all there already, this makes it a bit more obvious. First time setup might be a bit annoying, but afterwards it should be very easy to use, just run `./bin/audit-pr.js <repo> <pr>`.

### CODE REVIEW

**Comment by rxaviers** [comment]
@jzaefferer the clarification on the README looks fine to me :+1:. I have not walked through the steps themselves though.

**Comment by jzaefferer** [comment]
Okay. Please do when you get a chance. Until then we won't know what's missing...

**Comment by leobalter** [comment]
Works fine for me.

```
$ node bin/audit-pr.js qunit 836
{ sha: '2e244126c543f9a0f4f95b12a889a9241ae64105',
  state: 'success',
  url: 'http://contribute.jquery.org/CLA/status/?repo=qunit&sha=2e244126c543f9a0f4f95b12a889a9241ae64105',
  description: 'All authors have signed the CLA' }
```

Additional note: for this repo, we should handle the error when a `config.json` is not present. But, since the file is set, it won't be a problem anymore.

**Comment by jzaefferer** [comment]
I get this output without a `config.json`:

```sh
$ bin/audit-pr.js css-chassis 109
module.js:338
    throw err;
          ^
Error: Cannot find module '../config'
[...]
```
That's not a super clear error message, but for a one-time issues seems good enough.

Though I've added another mention of the file and its one required property in the "PR Auditing" section.

**Comment by jzaefferer** [comment]
Merged, let me know if there's an issue with the instructions or the binary.

**Comment by rxaviers** [comment]
:clap:

**Pull request merged**
