### PR TITLE
Multiple owners

### PR DESCRIPTION
**Pull request by csnover**
This PR allows a single instance to check PRs in multiple orgs. It also fixes existing bugs/test failures. ~~The commit here currently references a local branch for simple-log due to a defect in simple-log, see https://github.com/scottgonzalez/simple-log/pull/5. Once a new version is released I can update the package.json to match, and barring any other feedback this can be landed.~~ This is done.

The minor version number is bumped because there is an incompatible API change with the Repo type, which now accepts an owner & repo, instead of just repo. I didn’t see a lot of reason to try to maintain any backwards-compatibility here.

### CODE REVIEW

**Comment by dmethvin** [comment]
Awesome! Since a lot of the Dojo Foundation projects are spread across their own orgs this will come in really handy.

**Comment by jzaefferer** [comment]
Looks good to me.

**Comment by csnover** [comment]
So just in case it is unclear :) I don’t have the access to land this here or make any changes to the existing deployment, so at the moment someone else needs to carry this to completion.

**Comment by kborchers** [comment]
@csnover I have given you write access here as I think that makes sense and since @jzaefferer said it looks good that's probably enough to merge. Someone else will have to help you with the actual deployment though.

**Comment by csnover** [comment]
OK cool, thanks. Do you who that should be?

**Comment by kborchers** [comment]
Probably @scottgonzalez @jzaefferer or @arschmitz would be my guesses

**Comment by dmethvin** [comment]
What do we need to do to deploy this?

**Comment by scottgonzalez** [comment]
This uses our standard deployment process, so the actual deployment is just pushing a semver tag. However, this requires a config change, so we need to get that into the infrastructure repo. That side I'm not familiar with.

**Comment by scottgonzalez** [comment]
BTW, we never manually change version numbers in `package.json`. We use `npm version` to manage our versioning and tagging.

**Comment by dmethvin** [comment]
@aulvi or @gnarf do you know what's needed to after we push? I'm hesitant to tag and push until I know. :smile:

**Comment by scottgonzalez** [comment]
This is backward compatible with the existing confit, so pushing this before the configure change in the infrastructure repo is the correct thing to do.

**Pull request closed without merging**
