### PR TITLE
Remove name validation.

### LINKED ISSUE #54: Remove requirement to have 2 names in CLA signature
I have tried making this argument before and I think this PR sums up my argument nicely https://github.com/jquery/esprima/pull/1331

### PR DESCRIPTION
**Pull request by jdalton**
Removes name validation [since it was OK'd by legal](https://github.com/jquery/jquery-license/issues/54#issuecomment-146224110).

Closes #54.

### CODE REVIEW

**Comment by jzaefferer** [comment]
While #54 is still open, the comment you reference is followed by a lot more discussion, eventually resulting in an improvement to the error message (see https://github.com/jquery/jquery-license/commit/3685e418fad6cb44f3cd60038f3674699ce8e929). Removing the validation just increases the odds of commits with accidental bad author information, which I think is worse then manually verification a name every now and then. Even so, the later consensus in #54 seemed to go elsewhere, but that was never implemented.

**Comment by jdalton** [comment]
Yep, I saw the new error message. Trying to spur movement on old open issues.

So the new direction is to add a checkbox?

**Comment by dmethvin** [comment]
The way it works today is that if someone wants to sign with a single-word name we can approve that manually by noting it on the signature sheet. It doesn't seem to happen that often so I'm okay with the current process. I'd rather encourage a full name where possible and available but we have definitely accommodated single-word names for multiple reasons.

To @jdalton's point though, if this is the resolution we should close #54 . It's mostly a policy/legal question so I'd prefer @kborchers to weigh in and decide.

**Comment by scottgonzalez** [comment]
This catches a lot of nonsense. Removing it will result in some bad data in AUTHORS.txt for many projects.

**Comment by jdalton** [comment]
> Removing it will result in some bad data in AUTHORS.txt for many projects.

AUTHORS.txt is generated from the jQuery Foundation Google Doc CLA data?

**Comment by scottgonzalez** [comment]
> Are project's AUTHORS.txt generated from the jQuery Foundation Google Doc CLA data?

Indirectly, yes. AUTHORS.txt is generated from git author info. The author info must match the CLA signature. The CLA verification tool verifies names are sane.

**Comment by jdalton** [comment]
I think that's a bit of a leap. That said I have no interest in the politics, bikeshedding, or outcome of this issue. I'd just like the old issue addressed or closed is all.

**Comment by arschmitz** [comment]
As a maintainer of multiple projects i would also prefer to keep the manual verification process. This is pretty rare and easy to fix.

**Comment by arschmitz** [comment]
@jdalton what do you mean by a leap the CLA process is directly what keeps the author info in check, and has been very effective at it in my experience.

**Comment by jdalton** [comment]
Naw, imma:

**Comment by nzakas** [comment]
Can we reopen and merge this now that legal has said it's ok? I'm still getting a fair amount of new contributors having a problem with name validation.

**Comment by kborchers** [comment]
I have not reviewed these actual changes again so a new PR may be needed but according to legal, as long as there is a name present it should be considered a valid signature and as long as the git author info matches that valid signature, the check should pass. If that is the case with these changes, then I think it is good to reopen and merge. There was some objection from a couple of projects using CLA signatures to sanitize AUTHORS.txt files so maybe give them a few days to consider changes needed on their end but beyond those couple of items, I say go for it.

**Comment by arschmitz** [comment]
@nzakas Im curious has the trouble you have had been with it requiring a 2 part name or it requiring the names match. id say 95% of the trouble I have with contributors and CLA is getting matching names almost never is it an issue with that they are using a single word name. 

This issue PR might be a little deceiving in the title. This does not remove name match verification only the requirement it be 2 words.

**Comment by nzakas** [comment]
@arschmitz the name match is the problem. I didn't realize this didn't just remove the check.

**Comment by kborchers** [comment]
Sorry and I should rephrase what I said. According to legal, as long as there is a name on the signature, it is valid whether or not it matches the git commit info. As long as email matches signature and commit, the check should pass.

**Pull request closed without merging**
