### PR TITLE
Validate: Replace error message for failed name validation

### LINKED ISSUE #54: Remove requirement to have 2 names in CLA signature
I have tried making this argument before and I think this PR sums up my argument nicely https://github.com/jquery/esprima/pull/1331

### PR DESCRIPTION
**Pull request by jzaefferer**
Replaces somewhat hostile language by pointing at the required process.

Fixes #54

### CODE REVIEW

**Comment by sfrisk** [comment]
Looks good to me, also it's nice to point out manual verification is needed.

**Comment by jzaefferer** [comment]
We also need to update the git user name validation to skip the validation. Otherwise we end up with something like this: http://contribute.jquery.org/CLA/status/?repo=css-chassis&sha=5f25cd2368904287afbc05e7efd3cbbe474652d0 Without the non-matching error, it would still complain about the commit's author name: https://github.com/jquery/jquery-license/blob/master/lib/repo/audit.js#L71

Easiest solution would be to drop that commit author email+name validation, and only rely on the signature validation. If the signature is valid and matches the commit, the commit must also be valid. It might take longer to show the right message to the user, but that seems like an acceptable solution.

**Comment by gnarf** [comment]
:+1: better for now, lets keep #54 open for a bit though and evaluate different options, I think this message still needs more context or something, but this quick change is a definite improvement for now

**Comment by scottgonzalez** [comment]
+1 to @gnarf's suggestion.

**Comment by scottgonzalez** [comment]
> Easiest solution would be to drop that commit author email+name validation, and only rely on the signature validation. If the signature is valid and matches the commit, the commit must also be valid. It might take longer to show the right message to the user, but that seems like an acceptable solution.

Sounds good.

**Comment by jzaefferer** [comment]
Updated. Apart from the changes suggested above, I also updated the commit message to use "Ref" instead of "Fixes", so #54 will stay open when landing this.

**Comment by scottgonzalez** [comment]
Looks good.

**Pull request merged**
